---
abstract: "prepare unicode stream to be encoded as cp1251\r"
author:
  - 'liosha <liosha@cpan.org>'
build_requires:
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlIO-via-PrepareCP1251
requires:
  Data::Dumper: 0
  Unicode::Normalize: 0
  autodie: 0
  charnames: 0
  perl: 5.010
  utf8: 0
version: 0.01
